[build]
  command = "npm run build:netlify"
  publish = "out"

[build.environment]
  NEXT_PUBLIC_SUPABASE_URL = "https://wfieixqmazctqduzkzpd.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndmaWVpeHFtYXpjdHFkdXprenBkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzMjU2MDIsImV4cCI6MjA2MTkwMTYwMn0.en0v1W9PbfWEU_gY4laZucHT6lsH6RBLCbyciRqU9pU"
  NODE_VERSION = "18"
  NEXT_PUBLIC_NETLIFY = "true"

# Use the Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle Next.js routes
[[redirects]]
  from = "/_next/*"
  to = "/_next/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/api/:splat"
  status = 200

# Handle all other routes - this is critical for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
