[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_SUPABASE_URL = "https://wfieixqmazctqduzkzpd.supabase.co"
  # NEXT_PUBLIC_SUPABASE_ANON_KEY is set in the Netlify UI

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
